<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.crane199709</groupId>
        <artifactId>saas-forge</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>saas-forge-openapi-contracts</artifactId>
    <name>saas-forge-openapi-contracts</name>
    <packaging>pom</packaging>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
        <typescript.client.output>${project.build.directory}/generated-typescript-client</typescript.client.output>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.openapitools</groupId>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-typescript-api-client</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <inputSpec>${maven.multiModuleProjectDirectory}/saas-forge-contracts/saas-forge-openapi-contracts/v1.yaml</inputSpec>
                            <generatorName>typescript-fetch</generatorName>
                            <output>${typescript.client.output}</output>
                            <configOptions>
                                <useSingleRequestParameter>true</useSingleRequestParameter>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>standalone-typescript-client</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.openapitools</groupId>
                        <artifactId>openapi-generator-maven-plugin</artifactId>
                        <executions>
                            <execution>
                                <id>generate-typescript-api-client</id>
                                <configuration>
                                    <configOptions>
                                        <importFileExtension>.js</importFileExtension>
                                    </configOptions>
                                </configuration>
                            </execution>
                            <execution>
                                <id>generate-console-typescript-api-client</id>
                                <phase>generate-sources</phase>
                                <goals><goal>generate</goal></goals>
                                <configuration>
                                    <inputSpec>${maven.multiModuleProjectDirectory}/saas-forge-contracts/saas-forge-openapi-contracts/v2.yaml</inputSpec>
                                    <generatorName>typescript-fetch</generatorName>
                                    <output>${typescript.client.output}/console</output>
                                    <configOptions>
                                        <useSingleRequestParameter>true</useSingleRequestParameter>
                                        <importFileExtension>.js</importFileExtension>
                                    </configOptions>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
