-- 仅管理员在全新独立数据库边界执行一次；登录秘密由受控凭据渠道另行设置。
CREATE ROLE project_migrator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE ROLE project_app LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOBYPASSRLS;
CREATE DATABASE project_db OWNER project_migrator;
REVOKE ALL ON DATABASE project_db FROM PUBLIC;
GRANT CONNECT ON DATABASE project_db TO project_app;
\connect project_db
REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO project_migrator;
GRANT USAGE ON SCHEMA public TO project_app;
