spring:
  application:
    name: project-service
  jackson:
    mapper:
      allow-coercion-of-scalars: false
    deserialization:
      fail-on-unknown-properties: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    local-cache-scope: STATEMENT
